### ISSUE TITLE
Where is 'generated_data.csv'?

### ISSUE THREAD

**Issue by x369903522** [LeoHink/lipogramGPT#1]
I can't find generated_data.csv. Could you upload it?

**Comment by LeoHink** [comment]
Hey, thanks for pointing this out. This was an old data import, which Is actually not needed anymore. I've removed those lines that import the data. I haven't had the chance to run it yet, as it takes some time, but it should work now. If issues persist, don't hesitate to let me know. If everything runs fine feel free to close the issue :)

**Comment by x369903522** [comment]
(邮件自动回复)谢鸿宸：感谢来信，我会尽快回复。
(This is an automatic reply, confirming that your e-mail was received.)Hongchen Xie: Thanks for your letter. I will reply as soon as possible.

**Comment by x369903522** [comment]
(邮件自动回复)谢鸿宸：感谢来信，我会尽快回复。
(This is an automatic reply, confirming that your e-mail was received.)Hongchen Xie: Thanks for your letter. I will reply as soon as possible.
